services:
  cards:
    image: "cards"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
networks:
  eazybank:
    driver: "bridge"