services:
  loans:
    image: "loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
networks:
  eazybank:
    driver: "bridge"