spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
         native:
#         search-locations: "classpath:/config"
          search-locations: "file:///Users//Mulik//Documents//config"   # from local file system

server:
  port: 8071