spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
#         native:
#         search-locations: "classpath:/config"
#          search-locations: "file:///Users//Mulik//Documents//config"   # from local file system
        git:
          uri: "https://github.com/rahulmulik9/Bank_Configuration.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8071